[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2


# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ayerajath"
    weight = 1

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/rajathaithal/"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/ayerajath"
    weight = 3